### ISSUE TITLE
CW

### ISSUE THREAD

**Issue by AbuHaya3** [MOHAMED19OS/SoftCam_Emu#11]
F 00011040 00000000 E511B1A7758FB2B6 ;ZZGAVA ENC (7.0E) **54E34D845DFABF16**
F 0813029F 00000000 A8C2DE4805AD44F6 ;Turan TV Azerbaijan (7.0E) **FTA NOW**

**Comment by MOHAMED19OS** [comment]
Thank you
https://github.com/MOHAMED19OS/SoftCam_Emu/commit/6fdfa57d7786931c72a5ce1e7b6b69b539949992
