### ISSUE TITLE
fix dead data

### ISSUE THREAD

**Issue by EnoSat** [MOHAMED19OS/SoftCam_Emu#3]
https://github.com/MOHAMED19OS/SoftCam_Emu/blob/main/Enigma2/SoftCam.Key

V 007400 dead
V 001C10 dead
V 030B00 missing algo for public
P 0009 missing algo for public
F more dead channels

**Comment by MOHAMED19OS** [comment]
Please if you have any new key or if test any key and are dead pleas tel me

**Comment by EnoSat** [comment]
ok
