### ISSUE TITLE
Biss 33e update

### ISSUE THREAD

**Issue by ciefp** [MOHAMED19OS/SoftCam_Emu#6]
F 0FA41011 00000000 40D360731DB97D53 ;BN TV  (33.0E)
F 0FA61031 00000000 40D360731DB97D53 ;OBN  (33.0E)
F 0FA51051 00000000 40D360731DB97D53 ;Prva BH  (33.0E)
F 0FA31021 00000000 40D360731DB97D53 ;Nova BH  (33.0E)
F 0FA11001 00000000 40D360731DB97D53 ;O Kanal  (33.0E)
F 0FA21041 00000000 40D360731DB97D53 ;UNA TV  (33.0E)

**Comment by MOHAMED19OS** [comment]
Thank you my Friend
all key Update
https://github.com/MOHAMED19OS/SoftCam_Emu/commit/e1aba006e7e147b4cb4169ec9cc20997b6a22010
