### ISSUE TITLE
ZZGAVA ENC (7.0E)

### ISSUE THREAD

**Issue by AbuHaya3** [MOHAMED19OS/SoftCam_Emu#8]
F 8C51F31D 00000000 C77657947DE11371 ;ZZGAVA ENC (7.0E)
الشفرة الصحيحه لها 4 قنوات فييد
F 00010200 00 16F7344176C2033B; ZZGAVAX ENCX (7.0E)
F 00010200 00 16F7344176C2033B; BEVRT ENCX (7.0E)

**Comment by MOHAMED19OS** [comment]
I' Update Key thank you

**Comment by MOHAMED19OS** [comment]
https://github.com/MOHAMED19OS/SoftCam_Emu/commit/52d877a7b9bf75040d0e6dbaaf195fb7733e471d
