### ISSUE TITLE
تصحيح القيم

### ISSUE THREAD

**Issue by AbuHaya3** [MOHAMED19OS/SoftCam_Emu#9]
القيم الصحيح وليس المذكوره بالملف
F 00010134 00 198819BA882020C8; Al Ahad HD (3.0E)
---
F 00010200 00 253499F2443436AE; AVA (7.0E)
F 00010200 00 A1AD2270BBBB9107; Simaye Azadi Iran National TV (7.0E)
---
F 1EE30134 00000000 AAAAAAFEBBBBBB31 ;Iran Press (21.6E)             (X iran Press biss2)
F 00010021 00 DEAB19A20816BCDA; Riyadh MCR (21.6E)
F 00010065 00 12AB34F1CD56EF12; MBC Maser (21.6E)
F 000200C9 00 12AB34F1CD56EF12; MBC Maser 2 (21.6E)
---
اضافة شفرات
F 00C507B2 00 7777776577777765; IRIB TV3 HD (26.0E)
F 00C707C6 00 7777776577777765; VARZESH HD (26.0E)
F 012F0BD6 00 1111113311111133; IRIB TV3 SD (26.0E)
F 01930FBE 00 7777776577777765; IRIB TEST 1 (26.0E)
F 01A1104A 00 7777776577777765; IRIB TEST 2 (26.0E)
----
اضافة شفرات
F 000103F2 00 002005250019566F; 1 TV Georgia (46.0E)
F 0002006F 00 1001102110017081; Idman TV (46.0E)
F 000B051F 00 1010103010101030; TEST2 (46.0E)

**Comment by MOHAMED19OS** [comment]
السلام عليكم
تم تحديث الشفرات شكرا ياخي
